# Generated by Django 5.1.5 on 2025-01-16 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livelihood', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='monthly_cost',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='weekly_cost',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='yearly_cost',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='income',
            name='monthly_cost',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='income',
            name='offset',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='income',
            name='weekly_cost',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='income',
            name='yearly_cost',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='income',
            name='yearly_increase',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
