# Generated by Django 5.1.5 on 2025-01-24 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livelihood', '0002_alter_expense_monthly_cost_alter_expense_weekly_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2024-12-11 09:49:26.991567+00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expense',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='name',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='income',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2024-12-11 09:49:26.991567+00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='income',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='income',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='income',
            name='name',
            field=models.TextField(null=True),
        ),
    ]
